[package]
name = "cubic"
version = "0.1.0"
authors = ["Kevin Brown <kevinbrown5124@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
